services:
  postgres:
    image: postgres:16
    container_name: osint-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: osint_user
      POSTGRES_PASSWORD: change_me
      POSTGRES_DB: osint_aggregator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U osint_user -d osint_aggregator"]
      interval: 5s
      timeout: 5s
      retries: 10

  neo4j:
    image: neo4j:5
    container_name: osint-neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  backend:
    build:
      context: ./backend
    container_name: osint-backend
    depends_on:
       postgres:
        condition: service_healthy

    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: osint_user
      POSTGRES_PASSWORD: change_me
      POSTGRES_DB: osint_aggregator
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

volumes:
  postgres_data:
  neo4j_data: